apiVersion: v1
kind: Pod
metadata:
  name: pod1
spec:
#  nodeName: virt-atv-control-plane
  containers:
  - name: pod1-container
    image: httpd:2.4.41-alpine
    
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: "Exists"
      effect: "NoSchedule"
    - key: node-role.kubernetes.io/master
      operator: "Exists"
      effect: "NoSchedule"


